export type FAQItem = {
  question: string;
  answer: string;
};

// Common language support answer used across FAQs
const LANGUAGE_SUPPORT_ANSWER =
  "Yes! We support a wide range of languages including all major Indian languages: Hindi, Tamil, Telugu, Kannada, Malayalam, Bengali, Marathi, Gujarati, Punjabi, Odia, Assamese, Urdu, Sindhi, Kashmiri, Konkani, Maithili, Dogri, Sanskrit, Nepali, Manipuri, and Bodo. We also support international languages like English, Spanish, and French. You can even create multilingual songs that blend multiple languages for a unique touch!";


export const HOMEPAGE_FAQ: FAQItem[] = [
  {
    question: "How to generate a song with AI?",
    answer: "You choose what you want to create like lyrics, mood, genre, language, or even a short idea. Melodia’s AI turns that input into a complete song with vocals, music, and structure in minutes. No instruments. No studio. Just your idea, finished as a song.",
  },
  {
    question: "Can you copyright an AI-generated song?",
    answer: "Yes, with a small but important detail. If you are the one providing the creative input and generating the song on Melodia, you own the rights to use it commercially or personally, based on your plan. You can release it, monetize it, or use it in videos. What this really means is you stay in control of how your music is used.",
  },
  {
    question: "Which is the best AI music generator?",
    answer: "The best AI music generator depends on what you want to create. If your focus is background music, some tools work well. If you want full songs with lyrics, vocals, and emotion, you need something built for songwriting, not just sound generation. Melodia is designed for complete songs, not just beats or loops.",
  },
  {
    question: "Which is the best AI song generator?",
    answer: "The best AI song generator is the one that feels creative, fast, and usable in the real world. Melodia stands out because it lets you generate lyrics, vocals, and music together, customize style and mood, and actually use the songs for content, brands, or releases. It’s built for creators, not just experimentation.",
  },
  {
    question: "Where can I use the music generated on Melodia Songs?",
    answer: "You can use music from Melodia Songs almost anywhere. That includes YouTube videos, Instagram Reels, Shorts, podcasts, ads, websites, games, presentations, and client projects. You can also use it for personal listening or commercial work. What matters is that the music is generated by you, which gives you the freedom to actually use it, not just store it.",
  },
  {
    question: "Can I upload the music from Melodia Songs on Spotify?",
    answer: "Yes, you can. Songs generated on Melodia Songs can be uploaded to Spotify, Apple Music, and other streaming platforms, as long as they follow the platform’s standard upload rules. This means you can release tracks under your own artist name and distribute them just like any other song.",
  },
  {
    question: "What languages do you support?",
    answer: LANGUAGE_SUPPORT_ANSWER,
  },
];


export const PRICING_FAQ: FAQItem[] = [
  {
    question: "What if I don't love my song?",
    answer:
      "Fully Custom includes 1 free revision and Pro Studio includes 2 free revisions. After you listen, if something feels off — the name pronunciation, the music style, or the vibe — you can tell us exactly what to fix and we'll regenerate it for free. Just tap 'Not happy?' on your song page.",
  },
  {
    question: "How long does it take to receive my personalized song?",
    answer:
      "NameDrop and Fully Custom are ready in minutes. Pro Studio is delivered within 24 hours as it involves expert review.",
  },
  {
    question: "How many audio versions do I get?",
    answer:
      "Every package generates 2 distinct AI audio versions of your song so you can pick the one that sounds best. These are separate from revisions — revisions let you fix specific issues and regenerate entirely.",
  },
  {
    question: "Can I edit the lyrics before the song is generated?",
    answer:
      "Yes. The Fully Custom and Pro Studio packages let you review and edit the AI-written lyrics before the song is created. You can refine the words until they feel exactly right.",
  },
  {
    question: "Can I share or download the song?",
    answer:
      "Yes. Once your song is ready, you can listen, share, and download it. All packages include sharing and download.",
  },
  {
    question: "What languages do you support for song creation?",
    answer: LANGUAGE_SUPPORT_ANSWER,
  },
  {
    question: "What if something goes wrong with generation or payment?",
    answer:
      "If you face a technical issue, contact support and we'll help resolve it. Refund eligibility and policies are described on the Refund Policy page.",
  },
];

export const OCCASION_FAQ: Record<string, FAQItem[]> = {
  weddings: [
    {
      question: "What details should I share for a wedding song?",
      answer:
        "Share the couple's names, how they met, key moments, and the vibe you want (romantic, fun, traditional). Mention the event (sangeet, haldi, reception, etc.) for better personalization.",
    },
    {
      question: "Can you create songs for specific ceremonies like Sangeet or Haldi?",
      answer:
        "Yes. You can request a song tailored for sangeet, haldi, baraat entry, or reception—just mention the ceremony and the energy you want.",
    },
    {
      question: "What languages do you support for wedding songs?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
    {
      question: "Can I create a song mixing multiple languages?",
      answer:
        "Absolutely! Many of our wedding songs blend Hindi with English, or combine regional languages like Tamil, Telugu, Punjabi, or Gujarati with Hindi for a truly unique and personal touch. Just mention your preferred language mix in the request.",
    },
  ],
  birthday: [
    {
      question: "What makes a birthday song feel truly personal?",
      answer:
        "Include the recipient's name, relationship, inside jokes, personality traits, and memorable moments. The more specific the details, the better the song feels.",
    },
    {
      question: "Can I make it funny or emotional?",
      answer:
        "Yes. You can choose the vibe—funny, energetic, heartfelt, or emotional—and we'll generate lyrics and music to match.",
    },
    {
      question: "Can I revise the lyrics if I want changes?",
      answer:
        "Yes. Depending on the package, you can refine lyrics and regenerate within your included edit limits.",
    },
    {
      question: "What languages can I create birthday songs in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "adult-birthday": [
    {
      question: "What makes a birthday song for an adult feel personal?",
      answer:
        "Include the recipient's name, your relationship, inside jokes, personality quirks, and memorable moments you've shared. The more specific the details, the more the song feels truly theirs rather than a generic birthday tune.",
    },
    {
      question: "Can I make it funny or emotional?",
      answer:
        "Yes. You can choose the vibe — a playful roast, an upbeat party anthem, or a heartfelt, emotional tribute — and we'll generate lyrics and music to match.",
    },
    {
      question: "Is it good for milestone birthdays like 30th, 50th, or 60th?",
      answer:
        "Absolutely. Milestone birthdays are one of the most popular reasons to gift a personalized song. Mention the milestone and the journey behind it, and we'll craft lyrics that honour the moment.",
    },
    {
      question: "What languages can I create birthday songs in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  anniversary: [
    {
      question: "What should I include for an anniversary song?",
      answer:
        "Share how you met, milestones, meaningful places, and what you admire about your partner. Mention the years together and the vibe (romantic, nostalgic, celebratory).",
    },
    {
      question: "Is it suitable for both dating and wedding anniversaries?",
      answer:
        "Yes. You can create songs for dating anniversaries, wedding anniversaries, or any relationship milestone.",
    },
    {
      question: "Can I choose a romantic style?",
      answer:
        "Yes. You can request a romantic style or a specific mood, and the song will be generated to match that feel.",
    },
    {
      question: "What languages are available for anniversary songs?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  romantic: [
    {
      question: "What kind of romantic songs can Melodia create?",
      answer:
        "Melodia creates all styles of romantic songs — Bollywood-inspired love ballads, acoustic serenades, contemporary R&B, and classical romantic compositions. Just share the vibe you want.",
    },
    {
      question: "Can I use a romantic song for a proposal?",
      answer:
        "Yes! Many users create personalized romantic songs for proposals, Valentine's Day surprises, and special romantic gestures. Include your love story details for the perfect proposal song.",
    },
    {
      question: "What details make a romantic song more personal?",
      answer:
        "Include how you met, pet names, shared memories, favorite places, inside jokes, and what you love about your partner. The more personal details, the more meaningful the song becomes.",
    },
    {
      question: "What languages are available for romantic songs?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  sangeet: [
    {
      question: "What makes a great Sangeet song?",
      answer:
        "A great Sangeet song is energetic, fun, and personal. Include the couple's names, funny stories about how they met, family member names for shoutouts, and the dance energy you want — from Bollywood to Bhangra.",
    },
    {
      question: "Can the Sangeet song include family members' names?",
      answer:
        "Absolutely! Many Sangeet songs include playful mentions of family members, the bride's squad, or the groom's friends. Just list the names and relationships you want included.",
    },
    {
      question: "How fast can I get a Sangeet song?",
      answer:
        "NameDrop and Fully Custom packages deliver instantly. The Pro Studio with expert crafting delivers within 24 hours — perfect for last-minute Sangeet preparations.",
    },
    {
      question: "What languages work best for Sangeet songs?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  haldi: [
    {
      question: "What should I include for a Haldi ceremony song?",
      answer:
        "Share the bride or groom's name, family details, the mood you want (traditional, playful, emotional), and any specific rituals or family customs you want referenced in the song.",
    },
    {
      question: "Can I get a Haldi song in a regional language?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
    {
      question: "Is the Haldi song suitable to play during the ceremony?",
      answer:
        "Yes. Haldi songs are crafted to match the festive, joyful energy of the ceremony. They work perfectly as background music or for family performances during the Haldi ritual.",
    },
    {
      question: "How is a Haldi song different from a Sangeet song?",
      answer:
        "Haldi songs tend to be more traditional, warm, and family-focused, capturing the intimacy of the Haldi ritual. Sangeet songs are typically higher energy and performance-oriented. Melodia tailors each song to the specific ceremony's vibe.",
    },
  ],
  mehndi: [
    {
      question: "What makes a Mehndi song special?",
      answer:
        "A Mehndi song celebrates the bride's journey and the colorful, festive spirit of the ceremony. Include the bride's name, her excitement, family traditions, and the joyful energy you want to capture.",
    },
    {
      question: "Can I create a Mehndi song in Rajasthani or Punjabi?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
    {
      question: "Can the song reference specific Mehndi traditions?",
      answer:
        "Yes. You can request references to specific rituals like applying mehndi, the bride's anticipation, traditional games, or family customs. Just mention what you'd like included.",
    },
    {
      question: "How quickly can I receive my Mehndi song?",
      answer:
        "Instant delivery with NameDrop and Fully Custom packages. The Pro Studio delivers within 24 hours with expert creative review.",
    },
  ],
  "ring-ceremony": [
    {
      question: "What details should I share for a ring ceremony song?",
      answer:
        "Share the couple's names, how they met, the proposal story, what you love about each other, and the mood you want (romantic, celebratory, emotional). The more details, the more personal the song.",
    },
    {
      question: "Can I play the song during the ring exchange?",
      answer:
        "Yes. Ring ceremony songs are crafted to be played during the ceremony itself — as background music during the ring exchange or as a dedicated musical moment in the celebration.",
    },
    {
      question: "What styles are available for ring ceremony songs?",
      answer:
        "You can choose from romantic ballads, classical compositions, Bollywood-style numbers, or contemporary love songs. Specify the style you prefer, and Melodia will match it.",
    },
    {
      question: "What languages are available for ring ceremony songs?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  lullaby: [
    {
      question: "Can a lullaby include my baby's name?",
      answer:
        "Yes! That's what makes Melodia lullabies special. The song features your child's name woven naturally into soothing, gentle lyrics created just for them.",
    },
    {
      question: "What age group are lullabies suitable for?",
      answer:
        "Melodia lullabies are suitable for babies, toddlers, and young children. The gentle melodies and soothing vocals help create a calming bedtime routine for children of all ages.",
    },
    {
      question: "Can I create a lullaby as a baby shower gift?",
      answer:
        "Absolutely! A personalized lullaby makes a unique and thoughtful baby shower or naming ceremony gift. New parents love receiving a custom song created for their little one.",
    },
    {
      question: "What languages are lullabies available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  kids: [
    {
      question: "What kind of kids songs can Melodia create?",
      answer:
        "Melodia creates fun, educational, and personalized songs for children — from songs about their favorite animals and hobbies to celebration songs for their achievements, starting school, or learning new things.",
    },
    {
      question: "Are the songs age-appropriate?",
      answer:
        "Yes. All kids songs are crafted with age-appropriate language, themes, and musical styles. You can specify the child's age for better customization.",
    },
    {
      question: "Can the song be about my child's specific interests?",
      answer:
        "Yes! Share your child's favorite things — animals, colors, sports, cartoon characters, hobbies — and we'll incorporate them into a personalized song that makes your child the star.",
    },
    {
      question: "What languages are kids songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  party: [
    {
      question: "What details make a great party song?",
      answer:
        "Share the occasion (birthday, New Year, graduation, reunion), the names of key people, the energy you want (upbeat, danceable, hype), and any specific themes or inside jokes for the group.",
    },
    {
      question: "Can I play the party song at an event?",
      answer:
        "Yes. Party songs are produced in studio quality and can be played through any sound system at your event — house parties, clubs, outdoor celebrations, or corporate gatherings.",
    },
    {
      question: "What music styles are available for party songs?",
      answer:
        "Choose from Bollywood dance, EDM, hip-hop, pop, bhangra, reggaeton, or any style you prefer. Just specify the vibe and Melodia will create the perfect party track.",
    },
    {
      question: "What languages are party songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  friendship: [
    {
      question: "What makes a friendship song personal?",
      answer:
        "Include your shared memories, inside jokes, adventures, how you met, and what makes your friendship special. The more personal details you share, the more meaningful the song becomes.",
    },
    {
      question: "Can I create a friendship song as a surprise gift?",
      answer:
        "Yes! Friendship songs make unforgettable surprise gifts for Friendship Day, birthdays, farewells, or just because. Many users create them to surprise their best friends.",
    },
    {
      question: "Can a friendship song be for a group of friends?",
      answer:
        "Absolutely. You can include multiple friends' names and shared group memories. The song can reference your entire friend group and the experiences that brought you together.",
    },
    {
      question: "What languages are friendship songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  apology: [
    {
      question: "How does a personalized apology song help?",
      answer:
        "A personalized apology song shows genuine effort and emotional depth beyond just saying sorry. It demonstrates that you care enough to create something meaningful, making your apology more sincere and memorable.",
    },
    {
      question: "What should I include in an apology song request?",
      answer:
        "Share the situation, what you're sorry for, your feelings, what the person means to you, and the tone you want (sincere, emotional, gentle). Be honest — it makes the song more authentic.",
    },
    {
      question: "Is an apology song appropriate for any relationship?",
      answer:
        "Yes. Apology songs work for partners, friends, parents, siblings, colleagues — anyone you want to make amends with through a heartfelt musical gesture.",
    },
    {
      question: "What languages are apology songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "corporate-events": [
    {
      question: "What corporate events can Melodia create songs for?",
      answer:
        "Melodia creates songs for company anniversaries, product launches, team building events, award ceremonies, employee appreciation, annual parties, brand celebrations, and any corporate occasion.",
    },
    {
      question: "Can the song incorporate company values or brand messaging?",
      answer:
        "Yes. Share your company name, values, achievements, team culture, and any specific messaging you want included. The song will be professional and on-brand.",
    },
    {
      question: "Are bulk orders available for corporate clients?",
      answer:
        "Yes. Melodia offers bulk order options for corporate clients who need multiple songs or custom packages. Contact us for special corporate pricing.",
    },
    {
      question: "What languages are corporate songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  farewell: [
    {
      question: "What should I include in a farewell song request?",
      answer:
        "Share the person's name, your shared experiences, memorable moments, what you'll miss, and your wishes for their future. Mention the context — retirement, job change, moving away, graduation.",
    },
    {
      question: "Can a farewell song be created for a group?",
      answer:
        "Yes. Farewell songs can reference an entire team, class, or friend group. Include multiple names and shared group experiences for a collective goodbye song.",
    },
    {
      question: "Is a farewell song suitable for a retirement celebration?",
      answer:
        "Absolutely. Retirement farewell songs honor years of dedication and achievement while wishing the person well in their next chapter. They make retirement celebrations truly memorable.",
    },
    {
      question: "What languages are farewell songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  siblings: [
    {
      question: "What occasions are sibling songs perfect for?",
      answer:
        "Sibling songs are perfect for Raksha Bandhan, Bhai Dooj, birthdays, weddings, farewells, or any moment you want to celebrate your brother or sister. They also make great surprise gifts.",
    },
    {
      question: "Can the song include childhood memories?",
      answer:
        "Yes! Childhood memories make sibling songs incredibly personal. Share your shared adventures, fights, inside jokes, and the bond that has grown over the years.",
    },
    {
      question: "Can I create a song for multiple siblings?",
      answer:
        "Yes. You can create a song that celebrates the bond between all your siblings, including everyone's names and shared family memories.",
    },
    {
      question: "What languages are sibling songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  parents: [
    {
      question: "What makes a song for parents meaningful?",
      answer:
        "Include specific memories — their sacrifices, lessons they taught you, family traditions, and what you admire about them. Personal details make the song deeply emotional and meaningful.",
    },
    {
      question: "Can I create separate songs for my mother and father?",
      answer:
        "Yes. You can create individual songs for your mother and father, each with unique memories and messages. You can also create a combined song celebrating both parents together.",
    },
    {
      question: "Is a parent song suitable for Mother's Day or Father's Day?",
      answer:
        "Absolutely. Personalized parent songs are one of the most popular gifts for Mother's Day, Father's Day, their birthdays, anniversaries, and family celebrations.",
    },
    {
      question: "What languages are parent songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  congratulations: [
    {
      question: "What achievements can I celebrate with a congratulations song?",
      answer:
        "Any achievement worth celebrating — graduations, promotions, new jobs, business launches, new homes, exam results, sports victories, or personal milestones. If someone accomplished something, Melodia can celebrate it in song.",
    },
    {
      question: "Can the song mention the specific achievement?",
      answer:
        "Yes. Share the achievement, the person's name, their journey to success, and what makes this milestone special. The song will specifically celebrate their accomplishment.",
    },
    {
      question: "What's the best vibe for a congratulations song?",
      answer:
        "Most congratulations songs are upbeat and celebratory, but you can choose any mood — from energetic party anthems to proud, emotional tributes. Specify the energy you want.",
    },
    {
      question: "What languages are congratulations songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "thank-you": [
    {
      question: "Who can I create a thank you song for?",
      answer:
        "Anyone who deserves heartfelt thanks — teachers, mentors, doctors, nurses, caregivers, parents, friends, coaches, or colleagues. A personalized thank you song is a unique way to show appreciation.",
    },
    {
      question: "What should I include in a thank you song request?",
      answer:
        "Share who you're thanking, what they did for you, how they impacted your life, specific memories, and the emotions you want to convey. The more details, the more meaningful the song.",
    },
    {
      question: "Is a thank you song appropriate for Teacher's Day?",
      answer:
        "Yes! Thank you songs are extremely popular for Teacher's Day, Doctor's Day, and similar appreciation days. They create a lasting tribute that goes beyond a card or gift.",
    },
    {
      question: "What languages are thank you songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "mothers-day": [
    {
      question: "What details should I share for a Mother's Day song?",
      answer:
        "Include your mom's name or what you call her, specific memories together, traits you admire, inside jokes, and anything you want her to hear on Mother's Day. The more concrete the details—places, milestones, phrases she says—the more the lyrics feel truly hers.",
    },
    {
      question: "How quickly can I create a Mother's Day song on Melodia?",
      answer:
        "NameDrop and Fully Custom packages produce your song quickly so you can personalize lyrics and audio in time for Mother's Day—often within minutes after you finalize your preferences. Pick a package that fits how much you want to refine edits before you gift it.",
    },
    {
      question: "Can I revise the lyrics before gifting the song?",
      answer:
        "Yes. Packages include lyric edits so you can tune wording and regenerate within your plan limits until it sounds exactly right before Mother's Day.",
    },
    {
      question: "Is a custom song a good Mother's Day gift?",
      answer:
        "It is hard to beat for emotional impact—a song made from your memories and message shows intent beyond a generic gift. Many families play it during brunch or a video call, or send it so she can replay it anytime.",
    },
    {
      question: "What languages can I create a Mother's Day song in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  motivational: [
    {
      question: "What kind of motivational songs can Melodia create?",
      answer:
        "Melodia creates gym anthems, career motivation songs, exam preparation boosters, sports pump-up tracks, and personal growth inspiration songs. Specify the context and energy you need.",
    },
    {
      question: "Can a motivational song include my name and goals?",
      answer:
        "Yes! That's what makes it personalized. Share your name, your specific goals, challenges you're overcoming, and the energy you need. The song will be your personal anthem.",
    },
    {
      question: "Can I use the song for my workout playlist?",
      answer:
        "Absolutely. Motivational songs are produced in high quality and can be added to any playlist — gym, running, morning routine, or pre-game warmup.",
    },
    {
      question: "What languages are motivational songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "devotional-spiritual": [
    {
      question: "What types of devotional songs can Melodia create?",
      answer:
        "Melodia creates personalized bhajans, kirtans, prayer songs, meditation music, and spiritual compositions for any faith tradition. Share your spiritual preferences and we'll create accordingly.",
    },
    {
      question: "Can I request a song for a specific deity or spiritual practice?",
      answer:
        "Yes. You can request songs dedicated to specific deities, spiritual practices, or religious occasions. Share the context and Melodia will craft reverent, meaningful lyrics.",
    },
    {
      question: "Are devotional songs appropriate for religious ceremonies?",
      answer:
        "Yes. Devotional songs are crafted with respect and reverence, suitable for puja, prayer gatherings, meditation sessions, and religious celebrations.",
    },
    {
      question: "What languages are devotional songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
  "festive-holiday": [
    {
      question: "What festivals can Melodia create songs for?",
      answer:
        "Melodia creates songs for all major festivals — Diwali, Holi, Eid, Christmas, Navratri, Pongal, Onam, Baisakhi, Makar Sankranti, Ganesh Chaturthi, Durga Puja, and any other celebration.",
    },
    {
      question: "Can the song include family traditions specific to our celebration?",
      answer:
        "Yes! Share your family's unique festival traditions, customs, and the way you celebrate. The song will capture your family's specific celebration style.",
    },
    {
      question: "Can I create a song for a specific festival greeting?",
      answer:
        "Absolutely. You can create a personalized Diwali greeting song, Holi celebration anthem, Eid mubarak song, or any festival-specific greeting that you can share with family and friends.",
    },
    {
      question: "What languages are festival songs available in?",
      answer: LANGUAGE_SUPPORT_ANSWER,
    },
  ],
};

// Homepage FAQ combining pricing and general questions
export const homepageFAQ: FAQItem[] = [
  {
    question: "What is Melodia?",
    answer:
      "Melodia is India's leading personalized song creation platform. It uses AI technology to transform your stories, memories, and emotions into custom songs with professional vocals and music. Melodia supports 20+ languages including Hindi, Tamil, Telugu, Kannada, Malayalam, Bengali, Marathi, Gujarati, Punjabi, and English. Songs are available for weddings, birthdays, anniversaries, and every occasion, starting at INR 199.",
  },
  {
    question: "How does personalized song creation work on Melodia?",
    answer:
      "Creating a personalized song on Melodia is simple: share details about your recipient and occasion, review and customize the AI-generated lyrics, and receive your studio-quality produced song with vocals and music. The entire process takes just minutes for instant packages. Melodia's lyrics-first approach ensures every song captures your unique story.",
  },
  {
    question: "What languages does Melodia support for song creation?",
    answer: LANGUAGE_SUPPORT_ANSWER,
  },
  {
    question: "What occasions can I create personalized songs for?",
    answer:
      "Melodia creates personalized songs for any occasion — Indian weddings (Sangeet, Haldi, Mehndi, reception), birthdays, anniversaries, romantic moments, farewells, corporate events, festivals (Diwali, Holi, Eid, Christmas), devotional purposes, friendships, apologies, congratulations, thank you messages, and more. If it's a moment worth celebrating, Melodia can create a song for it.",
  },
  {
    question: "How much does a personalized song cost on Melodia?",
    answer:
      "Melodia offers three packages: NameDrop at INR 199 (pick a template song & personalize it with a name, 2 song variants, instant delivery), Fully Custom at INR 599 (custom AI-written lyrics, edit & refine, 2 song variations, instant delivery), and Pro Studio at INR 1499 (expert-crafted lyrics & song, up to 2 revisions, WhatsApp support, 24-hour delivery). All packages include download and sharing.",
  },
  {
    question: "Can I preview lyrics before the song is produced?",
    answer:
      "Yes! Melodia lets you generate and preview your personalized lyrics before committing to song production. You can review, edit, and refine the lyrics to ensure they capture exactly what you want to express before the final song is produced.",
  },
];
