"use client";

import { createSongAction } from "@/lib/actions/song.actions";
import { useRouter, useSearchParams } from "next/navigation";
import { useRef, useState, useEffect, useCallback } from "react";
import { useToast } from "@/hooks/use-toast";
import PersonaSelectionModal from "@/components/admin/PersonaSelectionModal";
import { LanguageSelector } from "@/components/admin/LanguageSelector";
import { Loader2 } from "lucide-react";
import {
  useAdminGenerateLyricsPreview,
  type AdminGenerateLyricsPreviewPayload,
  type AdminGenerateLyricsPreviewResult,
} from "@/hooks/useAdminGenerateLyricsPreview";

interface Category {
  id: number;
  name: string;
  slug: string;
  sequence: number;
}

interface SongRequest {
  id: number;
  label: string;
  recipientDetails: string;
  occasion: string | null;
  createdAt: string;
}

interface SongRequestDetails {
  id: number;
  recipientDetails: string;
  occasion: string | null;
  languages: string;
  mood: string[] | null;
  songStory: string | null;
  mobile_number: string | null;
  email: string | null;
  createdAt: string;
}

export default function CreateSongPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [selectedCategories, setSelectedCategories] = useState<number[]>([]);
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [songRequests, setSongRequests] = useState<SongRequest[]>([]);
  const [songRequestsLoading, setSongRequestsLoading] = useState(true);
  const [selectedSongRequestId, setSelectedSongRequestId] =
    useState<string>("");
  const [requestDetails, setRequestDetails] =
    useState<SongRequestDetails | null>(null);
  const [requestDetailsLoading, setRequestDetailsLoading] = useState(false);
  const hasSubmittedRef = useRef(false);
  const [personaModalOpen, setPersonaModalOpen] = useState(false);
  const [selectedPersona, setSelectedPersona] = useState<{ id: number; sunoPersonaId: string; name: string } | null>(null);
  const [selectedLanguages, setSelectedLanguages] = useState<string[]>([]);
  // Controlled form fields for pre-fill from song request / lyrics generation
  const [title, setTitle] = useState("");
  const [musicStyle, setMusicStyle] = useState("");
  const [lyrics, setLyrics] = useState("");
  const [lyricsAutoGenerated, setLyricsAutoGenerated] = useState(false);
  const { generateLyrics, isGenerating: generatingLyrics } =
    useAdminGenerateLyricsPreview({
      onSuccess: useCallback((result: AdminGenerateLyricsPreviewResult) => {
        if (result.title != null) setTitle(result.title);
        if (result.lyrics != null) setLyrics(result.lyrics);
        if (result.musicStyle != null) setMusicStyle(result.musicStyle);
        setLyricsAutoGenerated(true);
        toast({
          title: "Lyrics and music style generated",
          description: "Form has been filled. You can edit and submit.",
        });
      }, [toast]),
    });
  // Refine lyrics (uses existing /api/refine-lyrics when request has a lyrics draft)
  const [lyricsDraftId, setLyricsDraftId] = useState<number | null>(null);
  const [refinePrompt, setRefinePrompt] = useState("");
  const [isRefining, setIsRefining] = useState(false);

  // Get requestId from URL
  const requestIdFromUrl = searchParams.get("requestId");

  // Fetch categories and song requests on component mount
  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const response = await fetch("/api/categories");
        const data = await response.json();
        if (data.success) {
          setCategories(data.categories);
        } else {
          console.error("Failed to fetch categories:", data.error);
        }
      } catch (error) {
        console.error("Error fetching categories:", error);
      } finally {
        setCategoriesLoading(false);
      }
    };

    const fetchSongRequests = async () => {
      try {
        const response = await fetch("/api/admin/song-requests");
        const data = await response.json();
        if (data.success) {
          setSongRequests(data.requests);
          if (requestIdFromUrl) {
            setSelectedSongRequestId(requestIdFromUrl);
          }
        } else {
          console.error("Failed to fetch song requests:", data.error);
        }
      } catch (error) {
        console.error("Error fetching song requests:", error);
      } finally {
        setSongRequestsLoading(false);
      }
    };

    fetchCategories();
    fetchSongRequests();
  }, [requestIdFromUrl]);

  // Fetch detailed request information when requestId is provided
  useEffect(() => {
    const fetchRequestDetails = async () => {
      if (!requestIdFromUrl) {
        setRequestDetails(null);
        return;
      }

      setRequestDetailsLoading(true);
      try {
        const response = await fetch(`/api/song-requests/${requestIdFromUrl}`);
        if (response.ok) {
          const data = await response.json();
          if (data.success && data.data?.songRequest) {
            const req = data.data.songRequest;
            setRequestDetails({
              id: req.id,
              recipientDetails: req.recipientDetails,
              occasion: req.occasion,
              languages: req.languages,
              mood: req.mood,
              songStory: req.songStory,
              mobile_number: req.mobile_number || null,
              email: req.email || null,
              createdAt: req.createdAt,
            });
            // Initialize languages from request if available
            if (req.languages) {
              const languagesArray = typeof req.languages === 'string'
                ? req.languages.split(',').map((l: string) => l.trim()).filter((l: string) => l.length > 0)
                : Array.isArray(req.languages) ? req.languages : [];
              setSelectedLanguages(languagesArray);
            }
            // Pre-fill title and lyrics from existing lyrics draft if present
            const draft = data.data?.lyricsDraft;
            if (draft?.title) setTitle(draft.title);
            if (draft?.lyrics) setLyrics(draft.lyrics);
            if (draft?.id) setLyricsDraftId(draft.id);
          }
        }
      } catch (error) {
        console.error("Error fetching request details:", error);
      } finally {
        setRequestDetailsLoading(false);
      }
    };

    fetchRequestDetails();
  }, [requestIdFromUrl]);

  const refineLyricsFromDraft = async () => {
    if (!lyricsDraftId || !refinePrompt.trim()) return;
    setIsRefining(true);
    try {
      const res = await fetch("/api/refine-lyrics", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          lyricsDraftId,
          editPrompt: refinePrompt.trim(),
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        toast({
          title: "Refine failed",
          description: data.error || "Please try again.",
          variant: "destructive",
        });
        return;
      }
      if (data.draft?.lyrics != null) setLyrics(data.draft.lyrics);
      if (data.draft?.title != null) setTitle(data.draft.title);
      if (data.draft?.id != null) setLyricsDraftId(data.draft.id);
      setRefinePrompt("");
      toast({
        title: "Lyrics updated",
        description: "Refined lyrics have been applied. You can refine again or submit.",
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Network error";
      toast({
        title: "Error",
        description: msg,
        variant: "destructive",
      });
    } finally {
      setIsRefining(false);
    }
  };

  const generateLyricsFromRequest = () => {
    if (!requestDetails) return;
    const languagesStr =
      typeof requestDetails.languages === "string"
        ? requestDetails.languages
        : "English";
    const moodInput = requestDetails.mood?.length
      ? Array.isArray(requestDetails.mood)
        ? requestDetails.mood
        : [String(requestDetails.mood)]
      : undefined;
    const payload: AdminGenerateLyricsPreviewPayload = {
      recipientDetails: requestDetails.recipientDetails.trim(),
      languages: languagesStr || "English",
      occassion: requestDetails.occasion?.trim() || undefined,
      songStory: requestDetails.songStory?.trim() || undefined,
      mood: moodInput,
      ...(selectedPersona ? { personaId: selectedPersona.id } : {}),
    };
    generateLyrics(payload);
  };

  const handleCategoryChange = (categoryId: number) => {
    setSelectedCategories((prev) =>
      prev.includes(categoryId)
        ? prev.filter((id) => id !== categoryId)
        : [...prev, categoryId]
    );
  };

  const handleSubmit = async (formData: FormData) => {
    // Guard against double-submits (fast double click / enter)
    if (hasSubmittedRef.current || isLoading) return;
    hasSubmittedRef.current = true;
    setIsLoading(true);
    setError(null);

    try {
      // Add selected categories to form data
      formData.set("selectedCategories", JSON.stringify(selectedCategories));

      // Add selected languages to form data
      formData.set("languages", JSON.stringify(selectedLanguages));

      // Add song request ID if selected
      if (selectedSongRequestId) {
        formData.set("songRequestId", selectedSongRequestId);
      }

      const result = await createSongAction(formData);

      if (result?.success && result.redirect) {
        toast({
          title: "Song created successfully!",
          description: "Redirecting to generation progress...",
          duration: 3000,
        });
        router.push(result.redirect);
      } else if (result?.error) {
        setError(result.error);
        toast({
          title: "Error creating song",
          description: result.error,
          variant: "destructive",
          duration: 5000,
        });
      }
    } catch (err) {
      const errorMessage = `An unexpected error occurred: ${err}`;
      setError(errorMessage);
      toast({
        title: "Unexpected error",
        description: errorMessage,
        variant: "destructive",
        duration: 5000,
      });
    } finally {
      setIsLoading(false);
      // allow future submissions only after a short tick to avoid race with router.push
      setTimeout(() => {
        hasSubmittedRef.current = false;
      }, 1000);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      if (isLoading || hasSubmittedRef.current) return;
      const form = e.currentTarget.form;
      if (form) {
        form.requestSubmit();
      }
    }
  };
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Create New Song</h1>
        <p className="mt-1 text-sm text-gray-500">
          Add a new song to the Melodia library
        </p>
      </div>

      {/* Song Request Details - Prominently Displayed */}
      {requestIdFromUrl && (
        <div className="bg-yellow-50 border-2 border-yellow-200 rounded-lg p-6">
          <h2 className="text-xl font-bold text-gray-900 mb-4">
            Song Request Details (Request #{requestIdFromUrl})
          </h2>
          {requestDetailsLoading ? (
            <div className="text-sm text-gray-500">
              Loading request details...
            </div>
          ) : requestDetails ? (
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="font-semibold text-gray-700">For:</span>
                  <span className="ml-2 text-gray-900">
                    {requestDetails.recipientDetails}
                  </span>
                </div>
              {requestDetails.occasion && (
                <div>
                  <span className="font-semibold text-gray-700">Occasion:</span>
                  <span className="ml-2 text-gray-900">
                    {requestDetails.occasion}
                  </span>
                </div>
              )}
              {requestDetails.languages && (
                <div>
                  <span className="font-semibold text-gray-700">Language:</span>
                  <span className="ml-2 text-gray-900">
                    {requestDetails.languages}
                  </span>
                </div>
              )}
              {requestDetails.mood && requestDetails.mood.length > 0 && (
                <div>
                  <span className="font-semibold text-gray-700">Mood:</span>
                  <span className="ml-2 text-gray-900">
                    {Array.isArray(requestDetails.mood)
                      ? requestDetails.mood.join(", ")
                      : requestDetails.mood}
                  </span>
                </div>
              )}
              {requestDetails.mobile_number && (
                <div>
                  <span className="font-semibold text-gray-700">Mobile:</span>
                  <span className="ml-2 text-gray-900">
                    {requestDetails.mobile_number}
                  </span>
                </div>
              )}
              {requestDetails.email && (
                <div>
                  <span className="font-semibold text-gray-700">Email:</span>
                  <span className="ml-2 text-gray-900">
                    {requestDetails.email}
                  </span>
                </div>
              )}
              {requestDetails.songStory && (
                <div className="md:col-span-2">
                  <span className="font-semibold text-gray-700">Story:</span>
                  <p className="mt-1 text-gray-900 whitespace-pre-wrap bg-white p-3 rounded border border-yellow-300">
                    {requestDetails.songStory}
                  </p>
                </div>
              )}
              </div>
              <div className="pt-2 border-t border-yellow-200">
                <button
                  type="button"
                  onClick={generateLyricsFromRequest}
                  disabled={generatingLyrics}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-yellow-600 text-white rounded-md hover:bg-yellow-700 disabled:opacity-60 disabled:cursor-not-allowed text-sm font-medium"
                >
                  {generatingLyrics ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Generating lyrics...
                    </>
                  ) : lyricsAutoGenerated ? (
                    "Regenerate lyrics from this request"
                  ) : (
                    "Generate lyrics from this request"
                  )}
                </button>
                <p className="mt-1 text-xs text-gray-600">
                  Fills the song title, lyrics, and music style below using the request details.
                </p>
              </div>
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              Request details not found
            </div>
          )}
        </div>
      )}

      <div className="bg-white shadow sm:rounded-lg">
        <div className="px-4 py-5 sm:p-6">
          <form action={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Persona (optional)
              </label>
              <div className="mt-2 flex items-center gap-3">
                <button
                  type="button"
                  className="px-3 py-2 rounded-md bg-purple-600 text-white hover:bg-purple-700 text-sm"
                  onClick={() => setPersonaModalOpen(true)}
                >
                  {selectedPersona ? "Change Persona" : "Choose Persona"}
                </button>
                {selectedPersona && (
                  <div className="text-sm text-gray-700">
                    <span className="font-medium">{selectedPersona.name}</span>
                    <span className="ml-2 text-gray-500">({selectedPersona.sunoPersonaId})</span>
                    <button
                      type="button"
                      className="ml-3 text-xs text-red-600 hover:underline"
                      onClick={() => setSelectedPersona(null)}
                    >
                      Clear
                    </button>
                  </div>
                )}
              </div>
              <input type="hidden" name="personaId" value={selectedPersona?.sunoPersonaId || ""} />
              <p className="mt-1 text-xs text-gray-500">
                If a persona is selected, style will be omitted from generation.
              </p>
            </div>
            <div>
              <label
                htmlFor="title"
                className="block text-sm font-medium text-gray-700"
              >
                Song Title *
              </label>
              <input
                type="text"
                name="title"
                id="title"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
                placeholder="Enter song title"
              />
            </div>

            <div>
              <label
                htmlFor="songRequestId"
                className="block text-sm font-medium text-gray-700"
              >
                Link to Song Request
              </label>
              {songRequestsLoading ? (
                <div className="mt-1 text-sm text-gray-500">
                  Loading song requests...
                </div>
              ) : (
                <select
                  name="songRequestId"
                  id="songRequestId"
                  value={selectedSongRequestId}
                  onChange={(e) => setSelectedSongRequestId(e.target.value)}
                  disabled={!!requestIdFromUrl}
                  className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2 disabled:bg-gray-100"
                >
                  <option value="">None</option>
                  {songRequests.map((req) => (
                    <option key={req.id} value={req.id}>
                      {req.label}
                    </option>
                  ))}
                </select>
              )}
              <p className="mt-1 text-sm text-gray-500">
                {requestIdFromUrl
                  ? "This song will be linked to the selected request."
                  : "Linking a song to a request will associate it in the database."}
              </p>
            </div>

            <div>
              <label
                htmlFor="music_style"
                className="block text-sm font-medium text-gray-700"
              >
                Music Style *
              </label>
              <textarea
                name="music_style"
                id="music_style"
                rows={3}
                required={!selectedPersona}
                value={musicStyle}
                onChange={(e) => setMusicStyle(e.target.value)}
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
                placeholder="Enter the music style"
              />
              <p className="mt-1 text-sm text-gray-500">
                {selectedPersona
                   ? "Music style is optional when a persona is selected."
                   : "Enter the music style for the song generation"}
              </p>
            </div>

            <div>
              <label
                htmlFor="vocal_gender"
                className="block text-sm font-medium text-gray-700"
              >
                Vocal Gender (optional)
              </label>
              <select
                name="vocal_gender"
                id="vocal_gender"
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
              >
                <option value="">Default (Auto)</option>
                <option value="m">Male</option>
                <option value="f">Female</option>
              </select>
              <p className="mt-1 text-sm text-gray-500">
                Choose the preferred vocal gender for the generated song.
              </p>
            </div>

            <div>
              <label
                htmlFor="lyrics"
                className="block text-sm font-medium text-gray-700"
              >
                Lyrics *
              </label>
              <textarea
                name="lyrics"
                id="lyrics"
                rows={8}
                required
                value={lyrics}
                onChange={(e) => setLyrics(e.target.value)}
                onKeyDown={handleKeyDown}
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
                placeholder="Enter the lyrics for the song..."
              />
              <p className="mt-1 text-sm text-gray-500">
                These lyrics will be used as the prompt for song generation.
                Press Enter to submit, Shift+Enter for new line.
              </p>
            </div>

            {/* Refine lyrics with AI (uses existing /api/refine-lyrics when request has a lyrics draft) */}
            {requestIdFromUrl && (
              <div className="rounded-lg border border-gray-200 bg-gray-50 p-4">
                <h3 className="text-sm font-medium text-gray-900 mb-2">
                  Refine lyrics with AI
                </h3>
                {lyricsDraftId ? (
                  <>
                    <textarea
                      value={refinePrompt}
                      onChange={(e) => setRefinePrompt(e.target.value)}
                      placeholder="What changes would you like? (e.g. Make it more romantic, Add more Hindi lyrics, Change the chorus)"
                      rows={3}
                      className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
                    />
                    <div className="mt-2 flex items-center gap-2">
                      <button
                        type="button"
                        onClick={refineLyricsFromDraft}
                        disabled={isRefining || !refinePrompt.trim()}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-yellow-600 text-white rounded-md hover:bg-yellow-700 disabled:opacity-60 disabled:cursor-not-allowed text-sm font-medium"
                      >
                        {isRefining ? (
                          <>
                            <Loader2 className="h-4 w-4 animate-spin" />
                            Refining...
                          </>
                        ) : (
                          "Refine with AI"
                        )}
                      </button>
                      <span className="text-xs text-gray-500">
                        Uses the same refine API as the user flow; updates the form with the new version.
                      </span>
                    </div>
                  </>
                ) : (
                  <p className="text-sm text-gray-500">
                    Refine is available when this request already has generated lyrics (from the user flow). Generate lyrics from this request above, or link a request that has an existing lyrics draft.
                  </p>
                )}
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Categories
              </label>
              {categoriesLoading ? (
                <div className="mt-1 text-sm text-gray-500">
                  Loading categories...
                </div>
              ) : (
                <div className="mt-1 space-y-2">
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
                    {categories.map((category) => (
                      <label key={category.id} className="flex items-center">
                        <input
                          type="checkbox"
                          checked={selectedCategories.includes(category.id)}
                          onChange={() => handleCategoryChange(category.id)}
                          className="h-4 w-4 text-yellow-600 focus:ring-yellow-500 border-gray-300 rounded"
                        />
                        <span className="ml-2 text-sm text-gray-700">
                          {category.name}
                        </span>
                      </label>
                    ))}
                  </div>
                  {selectedCategories.length > 0 && (
                    <p className="text-sm text-gray-500">
                      Selected: {selectedCategories.length} categor
                      {selectedCategories.length === 1 ? "y" : "ies"}
                    </p>
                  )}
                </div>
              )}
              <p className="mt-1 text-sm text-gray-500">
                Optional: Select categories to help organize songs
              </p>
            </div>

            <div>
              <label
                htmlFor="negativeTags"
                className="block text-sm font-medium text-gray-700"
              >
                Negative Tags
              </label>
              <input
                type="text"
                name="negativeTags"
                id="negativeTags"
                className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-yellow-500 focus:border-yellow-500 sm:text-sm text-gray-900 px-3 py-2"
                placeholder="Enter negative tags separated by commas (e.g., Heavy Metal, Upbeat Drums)"
              />
              <p className="mt-1 text-sm text-gray-500">
                Optional: Specify what to avoid in the song generation
              </p>
            </div>

            <div>
              <LanguageSelector
                selectedLanguages={selectedLanguages}
                onChange={setSelectedLanguages}
                label="Languages"
                required={false}
              />
            </div>

            <div>
              <label className="flex items-center">
                <input
                  type="checkbox"
                  name="download_allowed"
                  className="h-4 w-4 text-yellow-600 focus:ring-yellow-500 border-gray-300 rounded"
                />
                <span className="ml-2 text-sm text-gray-700">
                  Allow download for this song
                </span>
              </label>
              <p className="mt-1 text-sm text-gray-500">
                If checked, users will be able to download this song from the
                library page
              </p>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-md p-4">
                <div className="flex">
                  <div className="flex-shrink-0">
                    <svg
                      className="h-5 w-5 text-red-400"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path
                        fillRule="evenodd"
                        d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </div>
                  <div className="ml-3">
                    <h3 className="text-sm font-medium text-red-800">Error</h3>
                    <div className="mt-2 text-sm text-red-700">{error}</div>
                  </div>
                </div>
              </div>
            )}

            <div className="flex flex-col sm:flex-row sm:justify-end gap-3">
              <a
                href="/song-admin-portal"
                className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500 w-full sm:w-auto text-center"
              >
                Cancel
              </a>
              <button
                type="submit"
                disabled={isLoading}
                className={`py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500 w-full sm:w-auto ${
                  isLoading
                    ? "bg-gray-400 text-gray-200 cursor-not-allowed"
                    : "bg-yellow-600 hover:bg-yellow-700 text-white"
                }`}
              >
                {isLoading ? "Creating Song..." : "Create Song"}
              </button>
            </div>
          </form>
        </div>
      </div>

      <PersonaSelectionModal
        open={personaModalOpen}
        onClose={() => setPersonaModalOpen(false)}
        onSelect={(p) => {
          setSelectedPersona(p);
          setPersonaModalOpen(false);
        }}
      />
    </div>
  );
}
